# Generated by Django 2.0.7 on 2018-07-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='EmpManager__last_na_4bb796_idx',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['phone'], name='EmpManager__phone_fc8325_idx'),
        ),
    ]
