# Generated by Django 2.0.7 on 2018-07-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManager', '0003_auto_20180716_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_siblings',
            field=models.BooleanField(default=False),
        ),
    ]
