# Generated by Django 2.0.7 on 2018-07-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManager', '0004_employee_has_siblings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='nothing@gmail.com', max_length=254),
        ),
    ]
