# Generated by Django 2.0.7 on 2018-07-17 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManager', '0005_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManager.Employee'),
        ),
    ]
