# Generated by Django 2.0.7 on 2018-07-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManager', '0009_auto_20180718_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='sibling',
            name='relation_type',
            field=models.CharField(choices=[('child', 'Child'), ('wife', 'wife'), ('husband', 'husband')], default='child', max_length=20),
        ),
    ]
