# Generated by Django 2.0.7 on 2018-07-18 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManager', '0010_sibling_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EmpManager.Position'),
            preserve_default=False,
        ),
    ]
