# Generated by Django 2.0.7 on 2018-07-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManager', '0011_salary_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='pos_type',
            field=models.CharField(max_length=30, verbose_name='Position'),
        ),
    ]
