# Generated by Django 2.0.7 on 2018-07-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManager', '0012_auto_20180718_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='total_deductions',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_salary',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='pos_type',
            field=models.CharField(max_length=30),
        ),
    ]
